AWS_ACCESS_KEY: "AKIAJYAPIQZY3BT2ZVLQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "apalepuflixter"
SECRET_KEY: "sk_test_9LayHreaombJJPbHyZ1yQF2S"
PUBLISHABLE_KEY: "pk_test_jrRW9u8WzmKjxP1hZFbwBtJl"